import * as sqlite3 from "sqlite3";

export const db = new sqlite3.Database(
  "./personnel.db",
  sqlite3.OPEN_READWRITE,
  handleError,
);

export function initialiseTable() {
  db.run(`CREATE TABLE IF NOT EXISTS personnel (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    enum TEXT,
    name TEXT NOT NULL,
    rank TEXT,
    postion TEXT,
    rank_date TEXT,
    platoon TEXT,
    squad TEXT,
    SHPK TEXT,
    postiona_assign_date TEXT,
    postiona_assign_num TEXT,
    draft_center TEXT,
    drafting_date TEXT,
    oath_date TEXT,
    mil_ticket_num TEXT,
    serving_before_2402 TEXT,
    ato_ooc_ubd_name TEXT,
    ato_ooc_ubd_spec TEXT,
    ato_ooc_ubd_serial TEXT,
    ato_ooc_ubd_num TEXT,
    ato_ooc_ubd_date_start TEXT,
    ato_ooc_ubd_date_end TEXT,
    previous_service_name TEXT,
    previous_service_spec TEXT,
    previous_service_order_num TEXT,
    previous_service_date_start TEXT,
    previous_service_date_end TEXT,
    VOS TEXT,
    VOS_codes TEXT,
    date_a7788 TEXT,
    edu_mil_uni TEXT,
    edu_mil_spec TEXT,
    edu_mil_year TEXT,
    edu_mil_country TEXT,
    birthdate TEXT,
    ipn_num TEXT,
    civ_id TEXT,
    civ_id_date TEXT,
    civ_id_who TEXT,
    bank_name TEXT,
    card_num TEXT,
    iban TEXT,
    driver_licens_category TEXT,
    driver_licens_date TEXT,
    city_of_birth TEXT,
    adress_city TEXT,
    adress_street TEXT,
    adress_apt TEXT,
    edu_type TEXT,
    edu_uni TEXT,
    edu_spec TEXT,
    edu_year TEXT,
    edu_country TEXT,
    phone_num TEXT,
    last_work TEXT,
    size_clothes TEXT,
    size_shoes TEXT,
    size_head TEXT,
    height TEXT,
    weight TEXT,
    marital_status TEXT,
    first_middle_last_name_wife_husband TEXT,
    first_middle_last_name_childern TEXT,
    first_middle_last_name_father TEXT,
    first_middle_last_name_mother TEXT,
    first_middle_last_name_brother TEXT,
    family_status TEXT,
    notes TEXT
  )`);
}

function handleError(err: Error | null) {
  if (err) console.error(err.message);
  console.log("Connected to the SQLite database.");
}
